version: "3.6"

services:
    powa-db:
        image: mariadb
        command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
        volumes:
            - db:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
        networks:
            - tf_gate

    powa:
        image: powa-ui:latest
        labels:
            traefik.enable: "true"
            traefik.port: 3000
            traefik.frontend.rule: "Host:${TRAEFIK_HOST}"
            traefik.docker.network: "tf_gate"
        volumes:
            - ./:/home/node/app
        ports:
            - ${TRAEFIK_PORTS}
        networks:
            - tf_gate
            - bdg
volumes:
    db:

networks:
    tf_gate:
        external: true
        name: tf_gate
    bdg:
        external: true
        name: bridge